### PR TITLE
Added custom target release

### PR DESCRIPTION
**Pull request by pbertera**
Added the possibility to define a custom minor version as target, in this way one can print the graph of the available upgrades within the same minor version.

### CODE REVIEW

**Comment by pamoedom** [comment]
Hi Pietro, thanks for your PR, much appreciated, but please note that script's goal is precisely to show the upgrade path options **between different minor versions** (for example 4.2.x to 4.3.x), this necessarily implies to target the next minor version channels.

NOTE: I don't like also the option of using env variables when launching the script, if we add something to handle this scenario in the future, it should be included as an optional variable.

Best Regards.

**Comment by pbertera** [comment]
Hi,
sure is clear. I did this adaptation to find the upgrade path from a very old 4.2 to 4.3, which is not included into the 4.3-stable channel. Makes sense to keep this script focused on jumping between minor versions. Thanks

**Comment by pamoedom** [comment]
Hi Pietro, take a look at latest version 1.4, I have added an option to generate same minor default channels if only the minor version is provided (4.2, 4.3), I think this is what you needed, right?
Regards.

**Comment by pbertera** [comment]
Yes! looks like what I needed ! thanks a lot

**Pull request closed without merging**
